Repository Hands-Up-Card-Open/HandsUpForUnity, pull requests merged in 2022-06, with the labels that each got.

#26 HUCO-151 | [fix] add the category custom id field and send it to the server
  HandsUp/Assets/CardViewScene/Scripts/Category/Category.cs
  HandsUp/Assets/CardViewScene/Scripts/Category/CategoryData.cs
  HandsUp/Assets/CardViewScene/Scripts/Category/CategoryManager.cs
  HandsUp/Assets/CardViewScene/Scripts/OthersManager.cs
Labels: bug

#27 HUCO 148, 149 - Delete Card and Category
  HandsUp/Assets/CardViewScene/Scenes/CardViewScene.unity
  HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
  HandsUp/UserSettings/EditorUserSettings.asset
Labels: enhancement

#28 Huco 153 - distinguish built-in and custom by color & create "전체" category
  HandsUp/Assets/CardViewScene/Prefabs/PR_CategoryItem.prefab
  HandsUp/Assets/CardViewScene/Scripts/Card/CardManager.cs
  HandsUp/Assets/CardViewScene/Scripts/Category/Category.cs
  HandsUp/Assets/CardViewScene/Scripts/Category/CategoryManager.cs
  HandsUp/Assets/CardViewScene/Scripts/CustomManager.cs
Labels: bug, enhancement

#29 Huco 150 - Fix Errors (Game load when login, View cards)
  HandsUp/Assets/CardViewScene/Scripts/Card/CardManager.cs
  HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
  HandsUp/Assets/Shared/Scripts/GameManager.cs
  HandsUp/UserSettings/EditorUserSettings.asset
Labels: bug

#31 Huco 158 - Fix Toggle Error
  HandsUp/Assets/CardViewScene/Scenes/CardViewScene.unity
  HandsUp/Assets/CardViewScene/Scripts/Category/Category.cs
  HandsUp/Assets/CardViewScene/Scripts/Category/CategoryManager.cs
  HandsUp/Assets/CardViewScene/Scripts/CustomManager.cs
  HandsUp/Assets/CardViewScene/Scripts/ToggleManager.cs
  HandsUp/Assets/CardViewScene/Scripts/ToggleManager.cs.meta
  HandsUp/UserSettings/EditorUserSettings.asset
Labels: bug

#33 HUCO-160 | [fix] init categories in custom page cases
  HandsUp/Assets/CardViewScene/Scripts/CustomManager.cs
  HandsUp/Assets/Shared/Scripts/BackBtnManager.cs
Labels: bug

#34 Huco 161 - edit host, port num & set screen ratios
  HandsUp/Assets/CardViewScene/Scenes/CardViewScene.unity
  HandsUp/Assets/GameScene/Scripts/CameraManager.cs
  HandsUp/Assets/OpeningScene/Scripts/DataManager.cs
  HandsUp/Assets/OpeningScene/Scripts/OpeningManager.cs
  HandsUp/Assets/Shared/bg.PNG
  HandsUp/Assets/Shared/bg.PNG.meta
  HandsUp/ProjectSettings/ProjectSettings.asset
  HandsUp/UserSettings/EditorUserSettings.asset
Labels: enhancement

#35 HUCO-167 | [fix] fix the error of custom category id in dropdown value
  HandsUp/Assets/CardViewScene/Scripts/CustomManager.cs
  HandsUp/Assets/CardViewScene/Scripts/EditManager.cs
Labels: bug

#36 HUCO-168 | [fix] make TTS Object don't destroyed
  HandsUp/Assets/CardViewScene/Scenes/CardViewScene.unity
  HandsUp/Assets/GameScene/Scenes/GameScene.unity
  HandsUp/Assets/GameSelectScene/Scenes/GameSelectScene.unity
  HandsUp/Assets/OpeningScene/Scenes/OpeningScene.unity
  HandsUp/UserSettings/EditorUserSettings.asset
Labels: bug

#38 HUCO-166 | [fix] camera permission error
  HandsUp/Assets/GameScene/Scripts/CameraManager.cs
  HandsUp/UserSettings/EditorUserSettings.asset
Labels: bug

#41 HUCO-169 | [fix] change getting text and texture directly
  HandsUp/Assets/Shared/Scripts/GameManager.cs
Labels: bug
